### ISSUE TITLE
希望能在这贴出订阅示例（服务器不一定要真的能使用）

### ISSUE THREAD

**Issue by q158073378252010** [eycorsican/rule-sets#1]
4.4核心版本的订阅不工作。
我不知道你是否改用哪个标准（v2rayN_ver2不行）
我建的订阅连接格式
https://github.com/q158073378252010/q158073378252010.github.io/raw/master/ios/rss.kit.txt

**Comment by eycorsican** [comment]
你看TF143的订阅好了没？

**Comment by q158073378252010** [comment]
没有

**Comment by eycorsican** [comment]
具体哪里不行呢？你上面给出的链接我测试是能正常更新的

**Comment by q158073378252010** [comment]
我也没弄明白重新安装后又正常了。
