### ISSUE TITLE
Adding some ads blocking rules please

### ISSUE THREAD

**Issue by Balnea** [eycorsican/rule-sets#2]
Please consider adding some ads blocking rules, such as for youtube, twitter, reddit or google.
It is pretty annoying when in the middle of videos the streamings are interrupted with ads and v2ray core seems unresponded so that a restart of the app is required.

**Comment by luxysiv** [comment]
Some ip ads of youtube,facebook,google.... in https. And this app not support MITM. So i think it cant block ads in Yt,Fb....Quantumult can do that,try it
